// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"github.com/ipavlov93/universe-demo/product-eventbus-pkg/message"
	"github.com/ipavlov93/universe-demo/product-sv/internal/domain"
	"github.com/ipavlov93/universe-demo/product-sv/internal/service/publisher"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFacade creates a new instance of MockFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFacade {
	mock := &MockFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFacade is an autogenerated mock type for the Facade type
type MockFacade struct {
	mock.Mock
}

type MockFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFacade) EXPECT() *MockFacade_Expecter {
	return &MockFacade_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type MockFacade
func (_mock *MockFacade) CreateProduct(ctx context.Context, product domain.Product) (int64, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) (int64, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) int64); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacade_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockFacade_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product domain.Product
func (_e *MockFacade_Expecter) CreateProduct(ctx interface{}, product interface{}) *MockFacade_CreateProduct_Call {
	return &MockFacade_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *MockFacade_CreateProduct_Call) Run(run func(ctx context.Context, product domain.Product)) *MockFacade_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Product
		if args[1] != nil {
			arg1 = args[1].(domain.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacade_CreateProduct_Call) Return(n int64, err error) *MockFacade_CreateProduct_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFacade_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, product domain.Product) (int64, error)) *MockFacade_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type MockFacade
func (_mock *MockFacade) DeleteProduct(ctx context.Context, ID int64) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFacade_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockFacade_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *MockFacade_Expecter) DeleteProduct(ctx interface{}, ID interface{}) *MockFacade_DeleteProduct_Call {
	return &MockFacade_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, ID)}
}

func (_c *MockFacade_DeleteProduct_Call) Run(run func(ctx context.Context, ID int64)) *MockFacade_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacade_DeleteProduct_Call) Return(err error) *MockFacade_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFacade_DeleteProduct_Call) RunAndReturn(run func(ctx context.Context, ID int64) error) *MockFacade_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type MockFacade
func (_mock *MockFacade) GetProductByID(ctx context.Context, ID int64) (domain.Product, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Product, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Product); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFacade_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockFacade_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *MockFacade_Expecter) GetProductByID(ctx interface{}, ID interface{}) *MockFacade_GetProductByID_Call {
	return &MockFacade_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, ID)}
}

func (_c *MockFacade_GetProductByID_Call) Run(run func(ctx context.Context, ID int64)) *MockFacade_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFacade_GetProductByID_Call) Return(obj domain.Product, err error) *MockFacade_GetProductByID_Call {
	_c.Call.Return(obj, err)
	return _c
}

func (_c *MockFacade_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (domain.Product, error)) *MockFacade_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductService creates a new instance of MockProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductService {
	mock := &MockProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductService is an autogenerated mock type for the ProductService type
type MockProductService struct {
	mock.Mock
}

type MockProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductService) EXPECT() *MockProductService_Expecter {
	return &MockProductService_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type MockProductService
func (_mock *MockProductService) CreateProduct(ctx context.Context, product domain.Product) (int64, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) (int64, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) int64); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductService_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockProductService_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product domain.Product
func (_e *MockProductService_Expecter) CreateProduct(ctx interface{}, product interface{}) *MockProductService_CreateProduct_Call {
	return &MockProductService_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *MockProductService_CreateProduct_Call) Run(run func(ctx context.Context, product domain.Product)) *MockProductService_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Product
		if args[1] != nil {
			arg1 = args[1].(domain.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductService_CreateProduct_Call) Return(n int64, err error) *MockProductService_CreateProduct_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockProductService_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, product domain.Product) (int64, error)) *MockProductService_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type MockProductService
func (_mock *MockProductService) DeleteProduct(ctx context.Context, productID int64) error {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductService_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockProductService_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int64
func (_e *MockProductService_Expecter) DeleteProduct(ctx interface{}, productID interface{}) *MockProductService_DeleteProduct_Call {
	return &MockProductService_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, productID)}
}

func (_c *MockProductService_DeleteProduct_Call) Run(run func(ctx context.Context, productID int64)) *MockProductService_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductService_DeleteProduct_Call) Return(err error) *MockProductService_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductService_DeleteProduct_Call) RunAndReturn(run func(ctx context.Context, productID int64) error) *MockProductService_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type MockProductService
func (_mock *MockProductService) GetProductByID(ctx context.Context, ID int64) (domain.Product, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Product, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Product); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductService_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockProductService_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *MockProductService_Expecter) GetProductByID(ctx interface{}, ID interface{}) *MockProductService_GetProductByID_Call {
	return &MockProductService_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, ID)}
}

func (_c *MockProductService_GetProductByID_Call) Run(run func(ctx context.Context, ID int64)) *MockProductService_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductService_GetProductByID_Call) Return(obj domain.Product, err error) *MockProductService_GetProductByID_Call {
	_c.Call.Return(obj, err)
	return _c
}

func (_c *MockProductService_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (domain.Product, error)) *MockProductService_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) CreateProduct(ctx context.Context, product domain.Product) (int64, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) (int64, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) int64); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockProductRepository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product domain.Product
func (_e *MockProductRepository_Expecter) CreateProduct(ctx interface{}, product interface{}) *MockProductRepository_CreateProduct_Call {
	return &MockProductRepository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *MockProductRepository_CreateProduct_Call) Run(run func(ctx context.Context, product domain.Product)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Product
		if args[1] != nil {
			arg1 = args[1].(domain.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) Return(productID int64, err error) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(productID, err)
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, product domain.Product) (int64, error)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProductByID provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) DeleteProductByID(ctx context.Context, ID int64) error {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProductRepository_DeleteProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProductByID'
type MockProductRepository_DeleteProductByID_Call struct {
	*mock.Call
}

// DeleteProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *MockProductRepository_Expecter) DeleteProductByID(ctx interface{}, ID interface{}) *MockProductRepository_DeleteProductByID_Call {
	return &MockProductRepository_DeleteProductByID_Call{Call: _e.mock.On("DeleteProductByID", ctx, ID)}
}

func (_c *MockProductRepository_DeleteProductByID_Call) Run(run func(ctx context.Context, ID int64)) *MockProductRepository_DeleteProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_DeleteProductByID_Call) Return(err error) *MockProductRepository_DeleteProductByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProductRepository_DeleteProductByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) error) *MockProductRepository_DeleteProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetProductByID(ctx context.Context, ID int64) (domain.Product, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.Product, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.Product); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockProductRepository_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID int64
func (_e *MockProductRepository_Expecter) GetProductByID(ctx interface{}, ID interface{}) *MockProductRepository_GetProductByID_Call {
	return &MockProductRepository_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, ID)}
}

func (_c *MockProductRepository_GetProductByID_Call) Run(run func(ctx context.Context, ID int64)) *MockProductRepository_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetProductByID_Call) Return(obj domain.Product, err error) *MockProductRepository_GetProductByID_Call {
	_c.Call.Return(obj, err)
	return _c
}

func (_c *MockProductRepository_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, ID int64) (domain.Product, error)) *MockProductRepository_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Publish(ctx context.Context, msg *message.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *message.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *message.Message
func (_e *MockPublisher_Expecter) Publish(ctx interface{}, msg interface{}) *MockPublisher_Publish_Call {
	return &MockPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, msg)}
}

func (_c *MockPublisher_Publish_Call) Run(run func(ctx context.Context, msg *message.Message)) *MockPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *message.Message
		if args[1] != nil {
			arg1 = args[1].(*message.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPublisher_Publish_Call) Return(err error) *MockPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, msg *message.Message) error) *MockPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrometheusService creates a new instance of MockPrometheusService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrometheusService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrometheusService {
	mock := &MockPrometheusService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrometheusService is an autogenerated mock type for the PrometheusService type
type MockPrometheusService struct {
	mock.Mock
}

type MockPrometheusService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrometheusService) EXPECT() *MockPrometheusService_Expecter {
	return &MockPrometheusService_Expecter{mock: &_m.Mock}
}

// IncProductsCreated provides a mock function for the type MockPrometheusService
func (_mock *MockPrometheusService) IncProductsCreated() {
	_mock.Called()
	return
}

// MockPrometheusService_IncProductsCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncProductsCreated'
type MockPrometheusService_IncProductsCreated_Call struct {
	*mock.Call
}

// IncProductsCreated is a helper method to define mock.On call
func (_e *MockPrometheusService_Expecter) IncProductsCreated() *MockPrometheusService_IncProductsCreated_Call {
	return &MockPrometheusService_IncProductsCreated_Call{Call: _e.mock.On("IncProductsCreated")}
}

func (_c *MockPrometheusService_IncProductsCreated_Call) Run(run func()) *MockPrometheusService_IncProductsCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPrometheusService_IncProductsCreated_Call) Return() *MockPrometheusService_IncProductsCreated_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPrometheusService_IncProductsCreated_Call) RunAndReturn(run func()) *MockPrometheusService_IncProductsCreated_Call {
	_c.Run(run)
	return _c
}

// IncProductsDeleted provides a mock function for the type MockPrometheusService
func (_mock *MockPrometheusService) IncProductsDeleted() {
	_mock.Called()
	return
}

// MockPrometheusService_IncProductsDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncProductsDeleted'
type MockPrometheusService_IncProductsDeleted_Call struct {
	*mock.Call
}

// IncProductsDeleted is a helper method to define mock.On call
func (_e *MockPrometheusService_Expecter) IncProductsDeleted() *MockPrometheusService_IncProductsDeleted_Call {
	return &MockPrometheusService_IncProductsDeleted_Call{Call: _e.mock.On("IncProductsDeleted")}
}

func (_c *MockPrometheusService_IncProductsDeleted_Call) Run(run func()) *MockPrometheusService_IncProductsDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPrometheusService_IncProductsDeleted_Call) Return() *MockPrometheusService_IncProductsDeleted_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPrometheusService_IncProductsDeleted_Call) RunAndReturn(run func()) *MockPrometheusService_IncProductsDeleted_Call {
	_c.Run(run)
	return _c
}

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Client provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Client() publisher.SQSClientAPI {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 publisher.SQSClientAPI
	if returnFunc, ok := ret.Get(0).(func() publisher.SQSClientAPI); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publisher.SQSClientAPI)
		}
	}
	return r0
}

// MockAdapter_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockAdapter_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockAdapter_Expecter) Client() *MockAdapter_Client_Call {
	return &MockAdapter_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockAdapter_Client_Call) Run(run func()) *MockAdapter_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAdapter_Client_Call) Return(sQSClientAPI publisher.SQSClientAPI) *MockAdapter_Client_Call {
	_c.Call.Return(sQSClientAPI)
	return _c
}

func (_c *MockAdapter_Client_Call) RunAndReturn(run func() publisher.SQSClientAPI) *MockAdapter_Client_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSQSClientAPI creates a new instance of MockSQSClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSQSClientAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSQSClientAPI {
	mock := &MockSQSClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSQSClientAPI is an autogenerated mock type for the SQSClientAPI type
type MockSQSClientAPI struct {
	mock.Mock
}

type MockSQSClientAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSQSClientAPI) EXPECT() *MockSQSClientAPI_Expecter {
	return &MockSQSClientAPI_Expecter{mock: &_m.Mock}
}

// GetQueueUrl provides a mock function for the type MockSQSClientAPI
func (_mock *MockSQSClientAPI) GetQueueUrl(ctx context.Context, params *sqs.GetQueueUrlInput, optFns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetQueueUrl")
	}

	var r0 *sqs.GetQueueUrlOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueUrlInput, ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueUrlInput, ...func(*sqs.Options)) *sqs.GetQueueUrlOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.GetQueueUrlOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.GetQueueUrlInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSQSClientAPI_GetQueueUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueUrl'
type MockSQSClientAPI_GetQueueUrl_Call struct {
	*mock.Call
}

// GetQueueUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.GetQueueUrlInput
//   - optFns ...func(*sqs.Options)
func (_e *MockSQSClientAPI_Expecter) GetQueueUrl(ctx interface{}, params interface{}, optFns ...interface{}) *MockSQSClientAPI_GetQueueUrl_Call {
	return &MockSQSClientAPI_GetQueueUrl_Call{Call: _e.mock.On("GetQueueUrl",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSQSClientAPI_GetQueueUrl_Call) Run(run func(ctx context.Context, params *sqs.GetQueueUrlInput, optFns ...func(*sqs.Options))) *MockSQSClientAPI_GetQueueUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.GetQueueUrlInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.GetQueueUrlInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSQSClientAPI_GetQueueUrl_Call) Return(getQueueUrlOutput *sqs.GetQueueUrlOutput, err error) *MockSQSClientAPI_GetQueueUrl_Call {
	_c.Call.Return(getQueueUrlOutput, err)
	return _c
}

func (_c *MockSQSClientAPI_GetQueueUrl_Call) RunAndReturn(run func(ctx context.Context, params *sqs.GetQueueUrlInput, optFns ...func(*sqs.Options)) (*sqs.GetQueueUrlOutput, error)) *MockSQSClientAPI_GetQueueUrl_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockSQSClientAPI
func (_mock *MockSQSClientAPI) SendMessage(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *sqs.SendMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) *sqs.SendMessageOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.SendMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSQSClientAPI_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSQSClientAPI_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.SendMessageInput
//   - optFns ...func(*sqs.Options)
func (_e *MockSQSClientAPI_Expecter) SendMessage(ctx interface{}, params interface{}, optFns ...interface{}) *MockSQSClientAPI_SendMessage_Call {
	return &MockSQSClientAPI_SendMessage_Call{Call: _e.mock.On("SendMessage",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *MockSQSClientAPI_SendMessage_Call) Run(run func(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options))) *MockSQSClientAPI_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.SendMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.SendMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSQSClientAPI_SendMessage_Call) Return(sendMessageOutput *sqs.SendMessageOutput, err error) *MockSQSClientAPI_SendMessage_Call {
	_c.Call.Return(sendMessageOutput, err)
	return _c
}

func (_c *MockSQSClientAPI_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)) *MockSQSClientAPI_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
